// 头部
var topMd = '<div id="top"><div id="top"><div class="wrapper"><div class="fl"><a href="http://www.114la.com" class="home" target="_blnak">114啦首页</a><i class="sq">|</i><a href="http://youxi.114la.com/" target="_blnak">游戏</a><a href="http://yinyue.114la.com/" target="_blnak">音乐</a><a href="http://meishi.114la.com/" target="_blnak">美食</a><a href="http://book.114la.com/" target="_blnak">小说</a><a href="http://tuan.114la.com/" target="_blnak">团购</a><a href="http://app.114la.com/" target="_blank">实用工具</a></div><div class="fr"><a href="http://www.114la.com/feedback" target="_blnak">意见反馈</a><i class="sq">|</i><a href="javascript:;" title="收藏114la影视" id="collet">收藏本页</a></div></div></div></div>';
$("body").prepend(topMd);


//底部
var y=new Date().getFullYear();
var bottomMd = '<div id="footer"><div class="wrapper clearfix"><dl><dt>热门站点</dt><dd><a href="http://book.114la.com/">好看的小说</a><a href="http://tianqi.114la.com/">天气预报</a><a href="http://tianqi.114la.com/air/">空气质量查询</a><a href="http://manhua.114la.com/">在线漫画</a><a href="http://tuan.114la.com/">团购大全</a><a href="http://meishi.114la.com/">美食天下</a><a href="http://meishi.114la.com/">菜谱大全</a><a href="/movie/">最新好看的电影</a><a href="/dianshi/">电视剧大全</a><a href="http://youxi.114la.com/">游戏大全</a><a href="http://app.114la.com/xingzuo/">星座运势</a><a href="http://app.114la.com/historyontoday/">历史上的今天</a></dd></dl><dl><dt>热门排行</dt><dd><a href="/top/movie-kehuan.html">科幻电影排行榜</a><a href="/top/movie-jingsong.html">惊悚电影排行榜</a><a href="/top/movie-xiju.html">喜剧电影排行榜</a><a href="/top/movie.html">电影排行榜</a><a href="/top/anime.html">动漫电影排行榜</a><a href="/top/tv-hanju.html">韩国电视剧排行榜</a><a href="/top/tv-meiju.html">美国电视剧排行榜</a></dd></dl><dl><dt>节目分类</dt><dd><a href="/movie/0-0-19.html">日本电影</a><a href="/movie/0-0-250.html">香港电影</a><a href="/movie/0-0-20.html">美国电影</a><a href="/movie/0-0-21.html">韩国电影</a><a href="/tv/0-0-277.html">泰国电视剧</a><a href="/tv/0-0-55.html">好看的美剧</a><a href="/tv/0-0-52.html">韩国电视剧</a><a href="/tv/0-0-53.html">香港电视剧</a><a href="/anime/0-0-99.html">日本动漫</a><a href="/zongyi/0-0-117.html">韩国综艺节目</a><a href="/zongyi/0-0-116.html">台湾综艺节目</a></dd></dl><p class="bhr"></p><ul class="fl"><li><a href="http://www.114la.com/about/about.html">关于114啦</a>|</li><li><a href="http://www.114la.com/about/ad.html">广告招商</a>|</li><li><a href="http://url.114la.com/">网站收录申请</a>|</li><li><a href="javascript:void(0)" onclick="divcenter()">意见反馈</a>|</li><li><a href="http://weibo.com/ylmf114la">官方微博</a></li></ul><p class="fr">©2005- '+y+' 114啦网址导航 粤ICP备05021225号</p></div></div>';
$("body").append(bottomMd);

//登录
var userlog = '<a href="/?ct=login">登录</a><a href="/?ct=register">注册</a>';
$(".userlog").html(userlog);

//影视名站
var siteLink ='<dt>影视名站<i></i></dt><dd><a href="http://v.qq.com/" target="_blnak" rel="nofollow">腾讯视频</a><i>|</i><a href="http://www.youku.com/" target="_blnak" rel="nofollow">优酷网</a><i>|</i><a href="http://www.iqiyi.com/" target="_blnak" rel="nofollow">爱奇艺</a><i>|</i><a href="http://www.letv.com/" target="_blnak" rel="nofollow">乐视网</a><i>|</i><a href="http://tv.sohu.com/" target="_blnak" rel="nofollow">搜狐视频</a><i>|</i><a href="http://www.kankan.com/" target="_blnak" rel="nofollow">迅雷看看</a><i>|</i><a href="http://www.v1.cn/" target="_blnak" rel="nofollow">第一视频</a><i>|</i><a href="http://www.tudou.com/" target="_blnak" rel="nofollow">土豆网</a><i>|</i><a href="http://www.m1905.com/vod/" target="_blnak" rel="nofollow">电影网</a><i>|</i><a href="http://www.pps.tv/" target="_blnak" rel="nofollow">PPS网络电视</a><i>|</i><a href="http://www.wasu.cn/" target="_blnak" rel="nofollow">华数TV</a><i>|</i><a href="/live/bjws.html" target="_blnak" rel="nofollow">电视直播</a><a href="/website/" target="_blnak" class="more" rel="nofollow">更多&gt;&gt;</a></dd>';
$(".siteLink").html(siteLink);